### ISSUE TITLE
login help

### ISSUE THREAD

**Issue by bobg2u** [bwilczynski/sonos-cli#5] opened 2020-01-19 01:40 UTC
I created sonos key and client secret. I'm using localhost:5000 as the redirect URL. I successfully log into my Sonos account, and click OKAY. The next response is invariably {"error":"invalid_request"}. I realize this isn't much information, but on the other hand I did not get very far into the process. ;-((
Can you help?

**Comment by bwilczynski** [comment] 2020-03-24 22:20
Please try with the latest version, it should solve issue with login

**Comment by benwoodward** [comment] 2020-04-07 02:56
I'm experiencing the same issue. The installed version is 0.3.1

EDIT: Latest version isn't available via Homebrew: 

```
❯ brew upgrade sonos-cli
Updating Homebrew...
Warning: bwilczynski/tap/sonos-cli 0.3.1 already installed
```

EDIT: Installed with `pip` and now working:

```
brew uninstall sonos-cli
pip3 install sonos-cli
```

**Comment by bobg2u** [comment] 2020-04-10 16:37
I just tried it, and unfortunately I still get same error. I verified my login credentials were correct.

**Comment by bwilczynski** [comment] 2020-04-13 17:30
@bobg2u which version do you use?

**Comment by bwilczynski** [comment] 2020-04-13 17:32
What login credentials are you referring to? It's not your username/password credentials that you use to login to Sonos but client_id and client_secret that you generate in developer portal when you add your application.

**Comment by bwilczynski** [comment] 2020-04-13 18:34
@benwoodward I just updated version on brew

**Comment by dredhorse** [comment] 2020-04-15 11:11
I have 0.3.5 and the same issue while using client-id and shared secret.

**Comment by Barry4679** [comment] 2020-04-15 13:35
I am no longer getting this issue with 0.3.5

Make sure that you are providing the correct login info. The documentation could be improved to better align with the names used at the Sonos site.

For the 1st login, after you issue the "sonos login" command in the app, you need to supply the key and the secret from the credentials at your "integration" at integration.sonos.com ...  and make sure that you are providing your "key", and not your "key name" ... ie. 
[these](https://www.dropbox.com/s/aj2hata7zed4ycn/sonos%20cli%20credentials.png?dl=0)

And then the login at the Sonos site requires the email address and password for your regular Sonos account, ie. the one that you use to sign into sonos.com, and where you can see all your registered devices etc.

**Comment by dredhorse** [comment] 2020-04-15 14:50
I think the issue is the redirect URI, could that be it?
Because I use the correct information, only other thing could be an adblocker in Chrome.

**Comment by dredhorse** [comment] 2020-04-15 14:52
that was the issue

**Comment by bwilczynski** [comment] 2020-04-15 15:51
@dredhorse is it working for you now? I agree with @Barry4679 that documentation needs improvement - I did this mostly for my own purposes in spare time and after I configured it once I haven't tried to repeat the process based solely on documentation. Then I realized someone else is trying to use it as well ;)

**Comment by dredhorse** [comment] 2020-04-15 15:53
yes after adding the correct uri like in the picture @Barry4679 provided. I did set it up with Keyboard Maestro and StreamDeck and can now control my sonos. Just need to figure out now how to get Playlists or Track info into the notifications via a KeyboardMaestro trigger.

**Comment by bwilczynski** [comment] 2020-04-15 16:12
Great. I am closing the issue. Thanks @Barry4679 for helping in resolving the issue. The documentation is now updated based on this discussion.

**Closed as completed by bwilczynski** 2020-04-15 16:12 UTC
